@startuml
!theme mars
object "CustomerApp" as CA
object "QuickRideApp" as RA
object "LocationAndMapping" as DS
object "PaymentGateway" as PG
object "NotificationService" as NS
object "PaymentProcessor" as PP
object "EmailService" as ES

NS <|-- CA
PG <|-- CA
NS <|-- RA
CA <|-- RA
CA <|-- DS
RA <|-- DS
PP <|-- PG
ES <|-- NS
CA <|-- NS
DS <|-- NS

@enduml