@startuml
object "CustomerApp" as CA
object "QuickRideApp" as QRA
object "LocationAndMapping" as LM
object "PaymentGateway" as PG
object "NotificationService" as NS
object "PaymentProcessor" as PP
object "EmailService" as ES

CA : UserName
CA : Password
CA : Booking History
CA : Addreess
QRA : Renting Car
QRA : Tracking Cars
QRA : Available Cars
LM : Latitude
LM : Longitude
LM : Source
LM : Destination
PG : Online Mode
PG : Cash Mode
NS : Booking Confirmation
NS : Status
PP : Payment Status
PP : Refund Status
ES : Subscribers
ES : Reviews


NS <|-- CA
PG <|-- CA
NS <|-- QRA
CA <|-- QRA
CA <|-- LM
QRA <|-- LM
PP <|-- PG
ES <|-- NS
CA <|-- NS
LM <|-- NS
@enduml